# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSpacerItem,
    QStatusBar, QTextBrowser, QVBoxLayout, QWidget)
import rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(545, 441)
        icon = QIcon()
        icon.addFile(u":/ROOT/1.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.Default = QAction(MainWindow)
        self.Default.setObjectName(u"Default")
        self.Exit = QAction(MainWindow)
        self.Exit.setObjectName(u"Exit")
        self.action300 = QAction(MainWindow)
        self.action300.setObjectName(u"action300")
        self.action300.setCheckable(True)
        self.action1200 = QAction(MainWindow)
        self.action1200.setObjectName(u"action1200")
        self.action1200.setCheckable(True)
        self.action2400 = QAction(MainWindow)
        self.action2400.setObjectName(u"action2400")
        self.action2400.setCheckable(True)
        self.action4800 = QAction(MainWindow)
        self.action4800.setObjectName(u"action4800")
        self.action4800.setCheckable(True)
        self.action9600 = QAction(MainWindow)
        self.action9600.setObjectName(u"action9600")
        self.action9600.setCheckable(True)
        self.action19200 = QAction(MainWindow)
        self.action19200.setObjectName(u"action19200")
        self.action19200.setCheckable(True)
        self.action38400 = QAction(MainWindow)
        self.action38400.setObjectName(u"action38400")
        self.action38400.setCheckable(True)
        self.action57600 = QAction(MainWindow)
        self.action57600.setObjectName(u"action57600")
        self.action57600.setCheckable(True)
        self.action74880 = QAction(MainWindow)
        self.action74880.setObjectName(u"action74880")
        self.action74880.setCheckable(True)
        self.action115200 = QAction(MainWindow)
        self.action115200.setObjectName(u"action115200")
        self.action115200.setCheckable(True)
        self.action230400 = QAction(MainWindow)
        self.action230400.setObjectName(u"action230400")
        self.action230400.setCheckable(True)
        self.action250000 = QAction(MainWindow)
        self.action250000.setObjectName(u"action250000")
        self.action250000.setCheckable(True)
        self.action500000 = QAction(MainWindow)
        self.action500000.setObjectName(u"action500000")
        self.action500000.setCheckable(True)
        self.action1000000 = QAction(MainWindow)
        self.action1000000.setObjectName(u"action1000000")
        self.action1000000.setCheckable(True)
        self.action2000000 = QAction(MainWindow)
        self.action2000000.setObjectName(u"action2000000")
        self.action2000000.setCheckable(True)
        self.action5N1 = QAction(MainWindow)
        self.action5N1.setObjectName(u"action5N1")
        self.action5N1.setCheckable(True)
        self.action6N1 = QAction(MainWindow)
        self.action6N1.setObjectName(u"action6N1")
        self.action6N1.setCheckable(True)
        self.action7N1 = QAction(MainWindow)
        self.action7N1.setObjectName(u"action7N1")
        self.action7N1.setCheckable(True)
        self.action8N1 = QAction(MainWindow)
        self.action8N1.setObjectName(u"action8N1")
        self.action8N1.setCheckable(True)
        self.action5N2 = QAction(MainWindow)
        self.action5N2.setObjectName(u"action5N2")
        self.action5N2.setCheckable(True)
        self.action6N2 = QAction(MainWindow)
        self.action6N2.setObjectName(u"action6N2")
        self.action6N2.setCheckable(True)
        self.action7N2 = QAction(MainWindow)
        self.action7N2.setObjectName(u"action7N2")
        self.action7N2.setCheckable(True)
        self.action8N2 = QAction(MainWindow)
        self.action8N2.setObjectName(u"action8N2")
        self.action8N2.setCheckable(True)
        self.action5E1 = QAction(MainWindow)
        self.action5E1.setObjectName(u"action5E1")
        self.action5E1.setCheckable(True)
        self.action5E2 = QAction(MainWindow)
        self.action5E2.setObjectName(u"action5E2")
        self.action5E2.setCheckable(True)
        self.action6E1 = QAction(MainWindow)
        self.action6E1.setObjectName(u"action6E1")
        self.action6E1.setCheckable(True)
        self.action6E2 = QAction(MainWindow)
        self.action6E2.setObjectName(u"action6E2")
        self.action6E2.setCheckable(True)
        self.action7E1 = QAction(MainWindow)
        self.action7E1.setObjectName(u"action7E1")
        self.action7E1.setCheckable(True)
        self.action7E2 = QAction(MainWindow)
        self.action7E2.setObjectName(u"action7E2")
        self.action7E2.setCheckable(True)
        self.action8E1 = QAction(MainWindow)
        self.action8E1.setObjectName(u"action8E1")
        self.action8E1.setCheckable(True)
        self.action8E2 = QAction(MainWindow)
        self.action8E2.setObjectName(u"action8E2")
        self.action8E2.setCheckable(True)
        self.action5O1 = QAction(MainWindow)
        self.action5O1.setObjectName(u"action5O1")
        self.action5O1.setCheckable(True)
        self.action5O2 = QAction(MainWindow)
        self.action5O2.setObjectName(u"action5O2")
        self.action5O2.setCheckable(True)
        self.action6O1 = QAction(MainWindow)
        self.action6O1.setObjectName(u"action6O1")
        self.action6O1.setCheckable(True)
        self.action6O2 = QAction(MainWindow)
        self.action6O2.setObjectName(u"action6O2")
        self.action6O2.setCheckable(True)
        self.action7O1 = QAction(MainWindow)
        self.action7O1.setObjectName(u"action7O1")
        self.action7O1.setCheckable(True)
        self.action7O2 = QAction(MainWindow)
        self.action7O2.setObjectName(u"action7O2")
        self.action7O2.setCheckable(True)
        self.action8O1 = QAction(MainWindow)
        self.action8O1.setObjectName(u"action8O1")
        self.action8O1.setCheckable(True)
        self.action8O2 = QAction(MainWindow)
        self.action8O2.setObjectName(u"action8O2")
        self.action8O2.setCheckable(True)
        self.style_dark = QAction(MainWindow)
        self.style_dark.setObjectName(u"style_dark")
        self.style_classic = QAction(MainWindow)
        self.style_classic.setObjectName(u"style_classic")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.sendingTextEdit = QLineEdit(self.centralwidget)
        self.sendingTextEdit.setObjectName(u"sendingTextEdit")
        self.sendingTextEdit.setMinimumSize(QSize(300, 30))

        self.horizontalLayout.addWidget(self.sendingTextEdit)

        self.Sending = QPushButton(self.centralwidget)
        self.Sending.setObjectName(u"Sending")
        self.Sending.setMinimumSize(QSize(80, 30))

        self.horizontalLayout.addWidget(self.Sending)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.recv_Text = QTextBrowser(self.centralwidget)
        self.recv_Text.setObjectName(u"recv_Text")

        self.verticalLayout.addWidget(self.recv_Text)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(35, 0))

        self.horizontalLayout_4.addWidget(self.label_2)

        self.port_select = QComboBox(self.centralwidget)
        self.port_select.addItem("")
        self.port_select.setObjectName(u"port_select")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.port_select.sizePolicy().hasHeightForWidth())
        self.port_select.setSizePolicy(sizePolicy1)
        self.port_select.setMinimumSize(QSize(100, 30))

        self.horizontalLayout_4.addWidget(self.port_select)


        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)

        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(50, 0))

        self.horizontalLayout_2.addWidget(self.label)

        self.end_select = QComboBox(self.centralwidget)
        self.end_select.addItem("")
        self.end_select.addItem("")
        self.end_select.addItem("")
        self.end_select.addItem("")
        self.end_select.setObjectName(u"end_select")
        self.end_select.setMinimumSize(QSize(100, 30))
        self.end_select.setMaximumSize(QSize(100, 16777215))

        self.horizontalLayout_2.addWidget(self.end_select)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)


        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.AutoLast = QRadioButton(self.centralwidget)
        self.AutoLast.setObjectName(u"AutoLast")
        self.AutoLast.setMinimumSize(QSize(120, 0))
        self.AutoLast.setLayoutDirection(Qt.RightToLeft)

        self.horizontalLayout_3.addWidget(self.AutoLast)

        self.Clear = QPushButton(self.centralwidget)
        self.Clear.setObjectName(u"Clear")
        self.Clear.setMinimumSize(QSize(80, 30))
        self.Clear.setMaximumSize(QSize(16777215, 30))

        self.horizontalLayout_3.addWidget(self.Clear)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 545, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menu)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menu)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menu)
        self.menu_4.setObjectName(u"menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.Default)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.Exit)
        self.menu_2.addAction(self.action300)
        self.menu_2.addAction(self.action1200)
        self.menu_2.addAction(self.action2400)
        self.menu_2.addAction(self.action4800)
        self.menu_2.addAction(self.action9600)
        self.menu_2.addAction(self.action19200)
        self.menu_2.addAction(self.action38400)
        self.menu_2.addAction(self.action57600)
        self.menu_2.addAction(self.action74880)
        self.menu_2.addAction(self.action115200)
        self.menu_2.addAction(self.action230400)
        self.menu_2.addAction(self.action250000)
        self.menu_2.addAction(self.action500000)
        self.menu_2.addAction(self.action1000000)
        self.menu_2.addAction(self.action2000000)
        self.menu_3.addAction(self.action5N1)
        self.menu_3.addAction(self.action5N2)
        self.menu_3.addAction(self.action6N1)
        self.menu_3.addAction(self.action6N2)
        self.menu_3.addAction(self.action7N1)
        self.menu_3.addAction(self.action7N2)
        self.menu_3.addAction(self.action8N1)
        self.menu_3.addAction(self.action8N2)
        self.menu_3.addAction(self.action5E1)
        self.menu_3.addAction(self.action5E2)
        self.menu_3.addAction(self.action6E1)
        self.menu_3.addAction(self.action6E2)
        self.menu_3.addAction(self.action7E1)
        self.menu_3.addAction(self.action7E2)
        self.menu_3.addAction(self.action8E1)
        self.menu_3.addAction(self.action8E2)
        self.menu_3.addAction(self.action5O1)
        self.menu_3.addAction(self.action5O2)
        self.menu_3.addAction(self.action6O1)
        self.menu_3.addAction(self.action6O2)
        self.menu_3.addAction(self.action7O1)
        self.menu_3.addAction(self.action7O2)
        self.menu_3.addAction(self.action8O1)
        self.menu_3.addAction(self.action8O2)
        self.menu_4.addAction(self.style_dark)
        self.menu_4.addAction(self.style_classic)

        self.retranslateUi(MainWindow)
        self.Exit.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4e32\u53e3\u52a9\u624b", None))
        self.Default.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u9ed8\u8ba4", None))
        self.Exit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.action300.setText(QCoreApplication.translate("MainWindow", u"300", None))
        self.action1200.setText(QCoreApplication.translate("MainWindow", u"1200", None))
        self.action2400.setText(QCoreApplication.translate("MainWindow", u"2400", None))
        self.action4800.setText(QCoreApplication.translate("MainWindow", u"4800", None))
        self.action9600.setText(QCoreApplication.translate("MainWindow", u"9600", None))
        self.action19200.setText(QCoreApplication.translate("MainWindow", u"19200", None))
        self.action38400.setText(QCoreApplication.translate("MainWindow", u"38400", None))
        self.action57600.setText(QCoreApplication.translate("MainWindow", u"57600", None))
        self.action74880.setText(QCoreApplication.translate("MainWindow", u"74880", None))
        self.action115200.setText(QCoreApplication.translate("MainWindow", u"115200", None))
        self.action230400.setText(QCoreApplication.translate("MainWindow", u"230400", None))
        self.action250000.setText(QCoreApplication.translate("MainWindow", u"250000", None))
        self.action500000.setText(QCoreApplication.translate("MainWindow", u"500000", None))
        self.action1000000.setText(QCoreApplication.translate("MainWindow", u"1000000", None))
        self.action2000000.setText(QCoreApplication.translate("MainWindow", u"2000000", None))
        self.action5N1.setText(QCoreApplication.translate("MainWindow", u"5N1", None))
        self.action6N1.setText(QCoreApplication.translate("MainWindow", u"6N1", None))
        self.action7N1.setText(QCoreApplication.translate("MainWindow", u"7N1", None))
        self.action8N1.setText(QCoreApplication.translate("MainWindow", u"8N1", None))
        self.action5N2.setText(QCoreApplication.translate("MainWindow", u"5N2", None))
        self.action6N2.setText(QCoreApplication.translate("MainWindow", u"6N2", None))
        self.action7N2.setText(QCoreApplication.translate("MainWindow", u"7N2", None))
        self.action8N2.setText(QCoreApplication.translate("MainWindow", u"8N2", None))
        self.action5E1.setText(QCoreApplication.translate("MainWindow", u"5E1", None))
        self.action5E2.setText(QCoreApplication.translate("MainWindow", u"5E2", None))
        self.action6E1.setText(QCoreApplication.translate("MainWindow", u"6E1", None))
        self.action6E2.setText(QCoreApplication.translate("MainWindow", u"6E2", None))
        self.action7E1.setText(QCoreApplication.translate("MainWindow", u"7E1", None))
        self.action7E2.setText(QCoreApplication.translate("MainWindow", u"7E2", None))
        self.action8E1.setText(QCoreApplication.translate("MainWindow", u"8E1", None))
        self.action8E2.setText(QCoreApplication.translate("MainWindow", u"8E2", None))
        self.action5O1.setText(QCoreApplication.translate("MainWindow", u"5O1", None))
        self.action5O2.setText(QCoreApplication.translate("MainWindow", u"5O2", None))
        self.action6O1.setText(QCoreApplication.translate("MainWindow", u"6O1", None))
        self.action6O2.setText(QCoreApplication.translate("MainWindow", u"6O2", None))
        self.action7O1.setText(QCoreApplication.translate("MainWindow", u"7O1", None))
        self.action7O2.setText(QCoreApplication.translate("MainWindow", u"7O2", None))
        self.action8O1.setText(QCoreApplication.translate("MainWindow", u"8O1", None))
        self.action8O2.setText(QCoreApplication.translate("MainWindow", u"8O2", None))
        self.style_dark.setText(QCoreApplication.translate("MainWindow", u"\u6697\u9ed1", None))
        self.style_classic.setText(QCoreApplication.translate("MainWindow", u"\u7ecf\u5178", None))
        self.Sending.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001", None))
#if QT_CONFIG(shortcut)
        self.Sending.setShortcut(QCoreApplication.translate("MainWindow", u"Enter", None))
#endif // QT_CONFIG(shortcut)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u7aef\u53e3", None))
        self.port_select.setItemText(0, QCoreApplication.translate("MainWindow", u"\u4e32\u53e3\u672a\u8fde\u63a5", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u675f\u7b26", None))
        self.end_select.setItemText(0, QCoreApplication.translate("MainWindow", u"\u65e0", None))
        self.end_select.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6362\u884c (\\n)", None))
        self.end_select.setItemText(2, QCoreApplication.translate("MainWindow", u"\u56de\u8f66 (\\r)", None))
        self.end_select.setItemText(3, QCoreApplication.translate("MainWindow", u"CR NL(\\r\\n)", None))

        self.AutoLast.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u8f6c\u5230\u884c\u5c3e", None))
#if QT_CONFIG(shortcut)
        self.AutoLast.setShortcut(QCoreApplication.translate("MainWindow", u"End", None))
#endif // QT_CONFIG(shortcut)
        self.Clear.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u7a7a", None))
#if QT_CONFIG(shortcut)
        self.Clear.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u83dc\u5355", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce2\u7279\u7387", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u901a\u4fe1\u683c\u5f0f", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u76ae\u80a4", None))
    # retranslateUi

